# Generated by Django 4.2.16 on 2025-01-01 12:26

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='Maximum size of 10MB', upload_to='covers/', validators=[book.models.Book.validate_image]),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
