# Generated by Django 4.2.25 on 2025-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=250, unique_for_date='created_at'),
            preserve_default=False,
        ),
    ]
