# Generated by Django 4.2.22 on 2025-06-19 22:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=245)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FormaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=245)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=245)),
                ('tipo_socio', models.CharField(choices=[('empresa', 'Empresa'), ('individual', 'Individual')], max_length=10)),
                ('telefone', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('morada', models.TextField(blank=True, default='', max_length=500)),
                ('data_registo', models.DateTimeField(default=django.utils.timezone.now)),
                ('actividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio_app.actividade')),
                ('forma', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio_app.formajuridica')),
            ],
        ),
    ]
