# Generated by Django 4.2.22 on 2025-06-20 11:34

from django.db import migrations, models
import socio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0002_categoria_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='image',
            field=models.ImageField(blank=True, upload_to='artigos/', validators=[socio_app.models.validate_image]),
        ),
    ]
