# Generated by Django 4.2.22 on 2025-06-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0003_artigo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='actividade',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='socio_app.actividade'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='forma',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='socio_app.formajuridica'),
        ),
    ]
