# Generated by Django 4.2.22 on 2025-06-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0004_alter_socio_actividade_alter_socio_forma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='tipo_artigo',
        ),
    ]
