# Generated by Django 4.2.25 on 2026-02-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0006_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['-data_publicacao'], name='socio_app_a_data_pu_2a2273_idx'),
        ),
    ]
