# Generated by Django 4.2.25 on 2026-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0007_alter_artigo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='tipo_artigo',
            field=models.CharField(choices=[('FE', 'Feactured'), ('NR', 'Normal')], default='NR', max_length=20),
        ),
    ]
