# Generated by Django 4.2.25 on 2026-03-02 14:20

from django.db import migrations, models
import socio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0009_artigo_views_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='artigos/', validators=[socio_app.models.validate_image])),
            ],
        ),
    ]
